### ISSUE TITLE
Will this work with swagger 1.1?

### ISSUE THREAD

**Issue by mangvlad** [method-inc/SwaggerToMarkdown#2]
It seems that in swagger 1.1 api-docs.json is the main file that describes all available resources ( multiple APIs).
What should be passed as parameters for the script. Can it be just a single URL to api-docs.json?

**Comment by foundrium** [comment]
I have not tried it, but looking at the current api-docs.json file I believe it should still work by providing this script the api-docs.json file or link.

**Comment by mangvlad** [comment]
So parameters.json and resources.json will not be needed?

**Comment by foundrium** [comment]
My mistake, didn't look closely enough at it :) Been a while since I looked at this code.

parameters.json is a file I created for the script. It is needed to seed data into the Markdown generated file. It is not related to the Swagger specification - only for this script.

resources.json and api-docs.json are the same file. So instead of passing in resources.json you should pass in the api-docs.json file.

**Comment by mangvlad** [comment]
I was about to run it but not sure where to ge gems that it is using...
(I am not familiar with ruby that much, but do have it and gem running. I have tried several gems from the list of required but they appear not available at rubygems.org repository)

**Comment by foundrium** [comment]
If you have gem installed on your system you should just be able to do "gem install gemname"

**Comment by mangvlad** [comment]
I was able to run it for pet store, but running it for my own 1.1 version I am getting this:

$ ruby swagger-to-markdown.rb -r http://localhost:8002/api-docs -p parameters.json -n Demo -o test.md -s http://localhost:8002/api-docs/security

swagger-to-markdown.rb:181:in `extract_resource_name': undefined method`-' for nil:NilClass (NoMethodError)
    from swagger-to-markdown.rb:31:in `write_api_to_markdown'
    from /Library/Ruby/Site/1.8/rubygems/core_ext/kernel_require.rb:45:in`each_with_index'
    from swagger-to-markdown.rb:29:in `each'
    from swagger-to-markdown.rb:29:in`each_with_index'
    from swagger-to-markdown.rb:29:in `write_api_to_markdown'
    from swagger-to-markdown.rb:26:in`open'
    from swagger-to-markdown.rb:26:in `write_api_to_markdown'
    from swagger-to-markdown.rb:17:in`enhance'
    from swagger-to-markdown.rb:253

This is what I have for api-docs:

``` javascript
{
    "apiVersion": "0.1",
    "swaggerVersion": "1.1",
    "basePath": "http://localhost:8002",
    "apis": [
        {
            "path": "/api-docs/security",
            "description": "none"
        },
        {
            "path": "/api-docs/regions",
            "description": "none"
        },
        {
            "path": "/api-docs/campuses",
            "description": "none"
        },
        {
            "path": "/api-docs/countries",
            "description": "none"
        },
        {
            "path": "/api-docs/files",
            "description": "none"
        }
    ]
}
```

This is what I have for api-docs/security:

``` javascript
{
    "apiVersion": "0.1",
    "swaggerVersion": "1.1",
    "basePath": "http://localhost:8002",
    "resourcePath": "/security",
    "apis": [
        {
            "path": "/security/token",
            "description": "Security related operations",
            "operations": [
                {
                    "parameters": [
                        {
                            "description": "Username, password, scope, grant type and clinet id are required",
                            "dataType": "string",
                            "required": true,
                            "paramType": "body",
                            "defaultValue": "xxxx"
                        },
                        {
                            "name": "content-type",
                            "description": "This has to be set to 'application/x-www-form-urlencoded'",
                            "dataType": "string",
                            "required": true,
                            "allowMultiple": false,
                            "allowableValues": {
                                "valueType": "LIST",
                                "values": [
                                    "application/x-www-form-urlencoded"
                                ]
                            },
                            "paramType": "header"
                        }
                    ],
                    "httpMethod": "POST",
                    "notes": "Returns a token",
                    "errorResponses": [
                        {
                            "code": 400,
                            "description": "invalid username"
                        },
                        {
                            "code": 403,
                            "description": "forbidden"
                        }
                    ],
                    "nickname": "getToken",
                    "summary": "Get token to use for authentication",
                    "responseClass": "Token"
                }
            ]
        },
        {
            "path": "/security/userprofile",
            "description": "Not displayed?",
            "operations": [
                {
                    "parameters": [
                        {
                            "name": "authorization",
                            "description": "Token",
                            "dataType": "string",
                            "required": true,
                            "allowMultiple": false,
                            "allowableValues": null,
                            "paramType": "header",
                            "defaultValue": "Bearer 7d7018f6-0673-4271-84a3-3c3823a83b60"
                        }
                    ],
                    "httpMethod": "GET",
                    "notes": "Use this operation to get currently logged in User's profile details.",
                    "errorResponses": [
                        {
                            "code": 400,
                            "description": "invalid id"
                        },
                        {
                            "code": 404,
                            "description": "pet not found"
                        }
                    ],
                    "nickname": "getUserProfile",
                    "summary": "User Profile details",
                    "produces": [
                        "application/json"
                    ],
                    "responseClass": "UserProfile"
                }
            ]
        }
    ],
    "models": {
        "Token": {
            "id": "Token",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "token_type": {
                    "type": "string"
                },
                "refresh_token": {
                    "type": "string"
                },
                "expires_in": {
                    "type": "long"
                },
                "scope": {
                    "type": "string"
                }
            }
        },
        "UserProfile": {
            "id": "UserProfile",
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                },
                "authorities": {
                    "type": "Array",
                    "items": {
                        "$ref": "Authority"
                    }
                },
                "accountNonExpired": {
                    "type": "boolean"
                },
                "accountNonLocked": {
                    "type": "string"
                },
                "credentialsNonExpired": {
                    "type": "boolean"
                },
                "enabled": {
                    "type": "boolean"
                },
                "clientId": {
                    "type": "long"
                },
                "userId": {
                    "type": "long"
                }
            }
        },
        "Authority": {
            "id": "Authority",
            "properties": {
                "authority": {
                    "type": "string"
                }
            }
        }
    }
}
```

All I get in test.md is:

``` markdown
#Demo 0.1 REST API
Base Path: http://localhost:8002

[Please add API specific content here]


##General Considerations
[Please add API specific content here]
```

**Comment by foundrium** [comment]
I would either use a ruby debugger or add some print statements and figure out why at line 181 in the script path is a nil object.
