### ISSUE TITLE
Try to convert swagger to markdown

### ISSUE THREAD

**Issue by voronnenok** [method-inc/SwaggerToMarkdown#3]
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- titleize (LoadError)
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in`require'
    from ./swagger-to-markdown.rb:7:in `<main>'

**Comment by hughneale** [comment]
gem2.0 install titleize

**Comment by nikitasingh** [comment]
gem install titleize
